### ISSUE TITLE
QuadPIO not working

### ISSUE THREAD

**Issue by robotcopper** [jondurrant/RPIPicoHC-SR04#1]
Hello,

First of all, thank you very much for your work. Currently, I'm trying to use multiple HC-SR04 sensors with microROS. I have experimented with your interrupt-based code but, when running with microROS, it's quite challenging to avoid system freezes. Consequently, I explored using your PIO-based code (without microROS, just your code without any modifications). Unfortunately, I'm not receiving any output – from what I can observe on my oscilloscope, no trigger is being emitted.

Do you have any suggestions that might help? I'm relatively new to using PIO.

**Comment by jondurrant** [comment]
Hi, The PIO library I use is this one, https://github.com/dangarbri/pico-distance-sensor.  There are further examples there.

I can't think off hand why you would not get a trigger pulse. The library requires that the trigger pin and echo are on adjacent GPIO pads with the trigger on the lower pad number. 

You use TriggerRead to send the trigger out. Then check for when is_sensing completes, before reading the resultant distance.

Might be worth reaching out to Daniel to see if he has any suggestions.
